use super::*;

#[test]
fn generated_bindings_include_protocol_method_maps() {
    let output = bindings();

    for expected in [
        "export const CLIENT_PROBE = \"client/probe\" as const;",
        "export const CLIENT_INITIALIZE = \"client/initialize\" as const;",
        "export const STATE_SUBSCRIBE = \"state/subscribe\" as const;",
        "export const STATE_UNSUBSCRIBE = \"state/unsubscribe\" as const;",
        "export const DIAGNOSTICS_GET_RUNTIME = \"diagnostics/getRuntime\" as const;",
        "export const SUPPORT_RECOVER_STUCK_SESSIONS = \"support/recoverStuckSessions\" as const;",
        "export const AGENT_PROBE = \"agent/probe\" as const;",
        "export const AGENT_AUTHENTICATE = \"agent/authenticate\" as const;",
        "export const AGENT_LIST_SESSIONS = \"agent/listSessions\" as const;",
        "export const AGENT_CREATE_CUSTOM = \"agent/createCustom\" as const;",
        "export const AGENT_UPDATE_CUSTOM_METADATA = \"agent/updateCustomMetadata\" as const;",
        "export const AGENT_REPLACE_CUSTOM = \"agent/replaceCustom\" as const;",
        "export const AGENT_DELETE_CUSTOM = \"agent/deleteCustom\" as const;",
        "export const AGENT_SET_ENABLED = \"agent/setEnabled\" as const;",
        "export const SETTINGS_GET_AGENT_DETAILS = \"settings/getAgentDetails\" as const;",
        "export const SETTINGS_GET_MCP_SERVERS = \"settings/getMcpServers\" as const;",
        "export const SETTINGS_GET_SKILLS = \"settings/getSkills\" as const;",
        "export const SETTINGS_GET_PREFERENCES = \"settings/getPreferences\" as const;",
        "export const SETTINGS_UPDATE_PREFERENCES = \"settings/updatePreferences\" as const;",
        "export const SETTINGS_GET_RUNTIME = \"settings/getRuntime\" as const;",
        "export const SETTINGS_UPDATE_RUNTIME = \"settings/updateRuntime\" as const;",
        "export const TASK_CREATE = \"task/create\" as const;",
        "export const TASK_SEND = \"task/send\" as const;",
        "export const TASK_SET_CONFIG_OPTION = \"task/setConfigOption\" as const;",
        "export const TASK_CANCEL = \"task/cancel\" as const;",
        "export const TASK_OPEN = \"task/open\" as const;",
        "export const TASK_MARK_READ = \"task/markRead\" as const;",
        "export const TASK_CHAT_PAGE = \"task/chatPage\" as const;",
        "export const TASK_TOOL_DETAIL = \"task/toolDetail\" as const;",
        "export const TASK_LIST = \"task/list\" as const;",
        "export const TASK_DISCARD = \"task/discard\" as const;",
        "export const PERMISSION_REQUEST = \"permission/request\" as const;",
        "export const SECRET_READ = \"secret/read\" as const;",
        "export const SHELL_SHOW_NOTIFICATION = \"shell/showNotification\" as const;",
        "export const SHELL_REVEAL_FILE = \"shell/revealFile\" as const;",
        "export const SHELL_RESOLVE_FILE_REVEAL = \"shell/resolveFileReveal\" as const;",
        "export type RequestParamsByMethod = {",
        "[CLIENT_PROBE]: ClientProbeParams;",
        "[CLIENT_INITIALIZE]: InitializeParams;",
        "[STATE_SUBSCRIBE]: StateSubscribeParams;",
        "[STATE_UNSUBSCRIBE]: StateUnsubscribeParams;",
        "[DIAGNOSTICS_GET_RUNTIME]: RuntimeDiagnosticsParams;",
        "[SUPPORT_RECOVER_STUCK_SESSIONS]: SupportRecoverStuckSessionsParams;",
        "[AGENT_PROBE]: AgentProbeParams;",
        "[AGENT_AUTHENTICATE]: AgentAuthenticateParams;",
        "[AGENT_LIST_SESSIONS]: AgentListSessionsParams;",
        "[AGENT_CREATE_CUSTOM]: AgentCreateCustomParams;",
        "[AGENT_UPDATE_CUSTOM_METADATA]: AgentUpdateCustomMetadataParams;",
        "[AGENT_REPLACE_CUSTOM]: AgentReplaceCustomParams;",
        "[AGENT_DELETE_CUSTOM]: AgentDeleteCustomParams;",
        "[AGENT_SET_ENABLED]: AgentSetEnabledParams;",
        "[SETTINGS_GET_AGENT_DETAILS]: AgentSettingsDetailsParams;",
        "[SETTINGS_GET_MCP_SERVERS]: SettingsMcpServersParams;",
        "[SETTINGS_GET_SKILLS]: SettingsSkillsParams;",
        "[SETTINGS_GET_PREFERENCES]: AppPreferencesParams;",
        "[SETTINGS_UPDATE_PREFERENCES]: AppPreferencesUpdateParams;",
        "[SETTINGS_GET_RUNTIME]: RuntimeSettingsParams;",
        "[SETTINGS_UPDATE_RUNTIME]: RuntimeSettingsUpdateParams;",
        "[TASK_CREATE]: TaskCreateParams;",
        "[TASK_SEND]: TaskSendParams;",
        "[TASK_SET_CONFIG_OPTION]: TaskSetConfigOptionParams;",
        "[TASK_CANCEL]: TaskCancelParams;",
        "[TASK_OPEN]: TaskOpenParams;",
        "[TASK_MARK_READ]: TaskMarkReadParams;",
        "[TASK_CHAT_PAGE]: TaskChatPageParams;",
        "[TASK_TOOL_DETAIL]: TaskToolDetailParams;",
        "[TASK_LIST]: TaskListParams;",
        "[TASK_DISCARD]: TaskDiscardParams;",
        "export type ResponseResultByMethod = {",
        "[CLIENT_PROBE]: ClientProbeResult;",
        "[CLIENT_INITIALIZE]: InitializeResult;",
        "[STATE_SUBSCRIBE]: StateSubscribeResult;",
        "[STATE_UNSUBSCRIBE]: StateUnsubscribeResult;",
        "[DIAGNOSTICS_GET_RUNTIME]: RuntimeDiagnosticsResult;",
        "[SUPPORT_RECOVER_STUCK_SESSIONS]: SupportRecoverStuckSessionsResult;",
        "[AGENT_PROBE]: AgentProbeResult;",
        "[AGENT_AUTHENTICATE]: AgentAuthenticateResult;",
        "[AGENT_LIST_SESSIONS]: AgentListSessionsResult;",
        "[AGENT_CREATE_CUSTOM]: AgentCreateCustomResult;",
        "[AGENT_UPDATE_CUSTOM_METADATA]: AgentUpdateCustomMetadataResult;",
        "[AGENT_REPLACE_CUSTOM]: AgentReplaceCustomResult;",
        "[AGENT_DELETE_CUSTOM]: AgentDeleteCustomResult;",
        "[AGENT_SET_ENABLED]: AgentSetEnabledResult;",
        "[SETTINGS_GET_AGENT_DETAILS]: AgentSettingsDetailsResult;",
        "[SETTINGS_GET_MCP_SERVERS]: SettingsMcpServersResult;",
        "[SETTINGS_GET_SKILLS]: SettingsSkillsResult;",
        "[SETTINGS_GET_PREFERENCES]: AppPreferencesResult;",
        "[SETTINGS_UPDATE_PREFERENCES]: AppPreferencesResult;",
        "[SETTINGS_GET_RUNTIME]: RuntimeSettingsResult;",
        "[SETTINGS_UPDATE_RUNTIME]: RuntimeSettingsResult;",
        "[TASK_CREATE]: TaskCreateResult;",
        "[TASK_SEND]: TaskSendResult;",
        "[TASK_SET_CONFIG_OPTION]: TaskSetConfigOptionResult;",
        "[TASK_CANCEL]: TaskCancelResult;",
        "[TASK_OPEN]: TaskOpenResult;",
        "[TASK_MARK_READ]: TaskMarkReadResult;",
        "[TASK_CHAT_PAGE]: TaskChatPageResult;",
        "[TASK_TOOL_DETAIL]: TaskToolDetailResult;",
        "[TASK_LIST]: TaskListResult;",
        "[TASK_DISCARD]: TaskDiscardResult;",
        "export type TypedClientRequest<M extends ProtocolMethod> = ClientRequestEnvelope<RequestParamsByMethod[M]> & {",
        "method: M;",
        "export type TypedClientResponse<M extends ProtocolMethod> = ResponseEnvelope<ResponseResultByMethod[M]>;",
        "export type ClientProbeRequest = TypedClientRequest<typeof CLIENT_PROBE>;",
        "export type ClientProbeResponse = ResponseEnvelope<ClientProbeResult>;",
        "export type ClientInitializeRequest = TypedClientRequest<typeof CLIENT_INITIALIZE>;",
        "export type ClientInitializeResponse = ResponseEnvelope<InitializeResult>;",
        "export type StateSubscribeResponse = ResponseEnvelope<StateSubscribeResult>;",
        "export type StateUnsubscribeResponse = ResponseEnvelope<StateUnsubscribeResult>;",
        "export type DiagnosticsGetRuntimeResponse = ResponseEnvelope<RuntimeDiagnosticsResult>;",
        "export type SupportRecoverStuckSessionsResponse = ResponseEnvelope<SupportRecoverStuckSessionsResult>;",
        "export type AgentProbeResponse = ResponseEnvelope<AgentProbeResult>;",
        "export type AgentAuthenticateResponse = ResponseEnvelope<AgentAuthenticateResult>;",
        "export type AgentListSessionsResponse = ResponseEnvelope<AgentListSessionsResult>;",
        "export type AgentCreateCustomResponse = ResponseEnvelope<AgentCreateCustomResult>;",
        "export type AgentUpdateCustomMetadataResponse = ResponseEnvelope<AgentUpdateCustomMetadataResult>;",
        "export type AgentReplaceCustomCleanup =",
        "export type AgentReplaceCustomHistoryPolicy = \"preserveHistoricalTasks\";",
        "export type SettingsMcpServerRecord =",
        "export type SettingsMcpServerTransport = \"stdio\" | \"http\" | \"sse\";",
        "export type SettingsMcpServerStatus = \"unknown\" | \"available\" | \"failed\" | \"disabled\";",
        "export type SettingsProjectionAvailability = \"available\" | \"unavailable\";",
        "export type SettingsSkillRecord =",
        "export type SettingsSkillStatus = \"valid\" | \"warning\" | \"invalid\" | \"shadowed\";",
        "export type SettingsProjectionNoticeSeverity = \"info\" | \"warning\" | \"error\";",
        "export type AgentReplaceCustomResponse = ResponseEnvelope<AgentReplaceCustomResult>;",
        "export type AgentDeleteCustomResponse = ResponseEnvelope<AgentDeleteCustomResult>;",
        "export type AgentSetEnabledResponse = ResponseEnvelope<AgentSetEnabledResult>;",
        "export type SettingsGetAgentDetailsResponse = ResponseEnvelope<AgentSettingsDetailsResult>;",
        "export type SettingsGetMcpServersResponse = ResponseEnvelope<SettingsMcpServersResult>;",
        "export type SettingsGetSkillsResponse = ResponseEnvelope<SettingsSkillsResult>;",
        "export type SettingsGetPreferencesResponse = ResponseEnvelope<AppPreferencesResult>;",
        "export type SettingsUpdatePreferencesResponse = ResponseEnvelope<AppPreferencesResult>;",
        "export type SettingsGetRuntimeResponse = ResponseEnvelope<RuntimeSettingsResult>;",
        "export type SettingsUpdateRuntimeResponse = ResponseEnvelope<RuntimeSettingsResult>;",
        "export type TaskCreateResponse = ResponseEnvelope<TaskCreateResult>;",
        "export type TaskSendResponse = ResponseEnvelope<TaskSendResult>;",
        "export type TaskSetConfigOptionResponse = ResponseEnvelope<TaskSetConfigOptionResult>;",
        "export type TaskCancelResponse = ResponseEnvelope<TaskCancelResult>;",
        "export type TaskOpenResponse = ResponseEnvelope<TaskOpenResult>;",
        "export type TaskChatPageResponse = ResponseEnvelope<TaskChatPageResult>;",
        "export type TaskToolDetailResponse = ResponseEnvelope<TaskToolDetailResult>;",
        "export type TaskListResponse = ResponseEnvelope<TaskListResult>;",
        "export type TaskDiscardResponse = ResponseEnvelope<TaskDiscardResult>;",
        "export type ServerRequestMethod = typeof PERMISSION_REQUEST | typeof QUESTION_REQUEST | typeof SECRET_READ | typeof SHELL_SHOW_NOTIFICATION | typeof SHELL_REVEAL_FILE;",
        "[PERMISSION_REQUEST]: PermissionRequestParams;",
        "[QUESTION_REQUEST]: QuestionRequestParams;",
        "[SECRET_READ]: SecretReadParams;",
        "[SHELL_SHOW_NOTIFICATION]: ShellShowNotificationParams;",
        "[SHELL_REVEAL_FILE]: ShellRevealFileParams;",
        "[PERMISSION_REQUEST]: PermissionRequestResponse;",
        "[QUESTION_REQUEST]: QuestionRequestResponse;",
        "[SECRET_READ]: SecretReadResponse;",
        "[SHELL_SHOW_NOTIFICATION]: ShellShowNotificationResponse;",
        "[SHELL_REVEAL_FILE]: ShellRevealFileResponse;",
        "[SHELL_RESOLVE_FILE_REVEAL]: ShellResolveFileRevealParams;",
        "[SHELL_RESOLVE_FILE_REVEAL]: ShellResolveFileRevealResult;",
        "export type TypedServerRequest<M extends ServerRequestMethod> = ServerRequestEnvelope<ServerRequestParamsByMethod[M]> & {",
        "export type PermissionRequestResponse =",
        "export type QuestionRequestParams =",
        "export type QuestionRequestResponse =",
        "export type SecretReadParams =",
        "export type ShellShowNotificationParams =",
        "export type ShellRevealFileParams =",
        "export type ShellResolveFileRevealParams =",
        "export type ShellResolveFileRevealResult =",
        "export type StateSubscribeResult =",
        "export type ClientProbeResult =",
        "export type ClientProbeLifecycle = \"running\" | \"draining\" | \"stopping\";",
        "export type SubscriptionScope =",
        "export type SubscriptionSnapshot =",
        "export type TaskSendIdempotencyKey = string & { readonly __openaideBrand: \"TaskSendIdempotencyKey\" };",
        "export type AppServerEvent = { previousCursor: EventCursor, cursor: EventCursor, scope: EventScope, payload: AppServerEventPayload, };",
        "export type ClientSnapshot =",
        "export type TaskSnapshot =",
        "pendingRequests?: Array<PendingRequestSnapshot>",
        "export type TaskPreparationSnapshot =",
        "export type TaskAgentConfigSnapshot =",
        "export type AgentSlashCommandSnapshot =",
        "export type AgentId = string & { readonly __openaideBrand: \"AgentId\" };",
    ] {
        assert!(
            output.contains(expected),
            "missing generated binding line: {expected}"
        );
    }
}
