use ts_rs::Config;

mod declarations;
mod method_constants;
mod method_maps;

pub fn bindings() -> String {
    let config = Config::default().with_large_int("number");
    let mut output = String::new();

    output.push_str("// This file is generated by openaide-app-server-protocol.\n");
    output.push_str("// Do not edit by hand. Run `npm run protocol:generate`.\n\n");
    method_constants::push_method_constants(&mut output);
    declarations::push_protocol_declarations(&mut output, &config);
    method_maps::push_method_maps(&mut output);

    output
}

#[cfg(test)]
mod tests;
