use ts_rs::Config;

mod declarations;
mod method_constants;
mod method_maps;

pub fn bindings() -> String {
    let config = Config::default().with_large_int("number");
    let mut output = String::new();

    output.push_str("// This file is generated by openaide-app-server-protocol.\n");
    output.push_str("// Do not edit by hand. Run `npm run protocol:generate`.\n\n");
    method_constants::push_method_constants(&mut output);
    declarations::push_protocol_declarations(&mut output, &config);
    method_maps::push_method_maps(&mut output);
    push_protocol_version(&mut output);

    // ts-rs emits a space before newlines around documented fields. Normalize
    // once at the generator boundary so checked-in bindings stay diff-clean.
    let mut normalized = output
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    normalized
}

/// A client states the version it was built against when it initializes.
fn push_protocol_version(output: &mut String) {
    let version = crate::client::APP_SERVER_PROTOCOL_VERSION;
    output.push_str(&format!(
        "\nexport const APP_SERVER_PROTOCOL_VERSION: ProtocolVersion = {{ major: {}, minor: {} }};\n",
        version.major, version.minor
    ));
}

#[cfg(test)]
mod tests;
