import type { TaskStatus } from "../runtime/primitives.js";
import type { WebviewSurfaceKind } from "./bootstrap.js";

export type WebviewTelemetryPayload = {
  event?: string;
  surface?: WebviewSurfaceKind | "invalid";
  task_id?: string;
  snapshot_request_id?: number;
  latest_snapshot_request_id?: number;
  snapshot_intent?: "open" | "refresh";
  reason?: string;
  request?: string;
  task_status?: TaskStatus;
  chat_items?: number;
  has_active_task?: boolean;
  error_name?: string;
  error_code?: string;
  error_message?: string;
  agent_id?: string;
  project_id?: string;
  session_list_request_id?: number;
  connection_id?: string;
  operation_id?: string;
  method?: string;
  scope_kind?: string;
  scope_key?: string;
  generation?: number;
  endpoint_revision?: number;
  attempt?: number;
  failure_count?: number;
  duration_ms?: number;
  retry_delay_ms?: number;
  timeout_ms?: number;
  after_sequence?: number;
  last_server_sequence?: number;
  frame_count?: number;
  queue_depth?: number;
  queued_uploads?: number;
  replica_count?: number;
  generation_count?: number;
  observed_replica_count?: number;
  transport_operation_kind?: string;
  http_status?: number;
  server_id?: string;
  previous_server_id?: string;
  next_server_id?: string;
  response_code?: string;
  error_kind?: string;
  previous_status?: string;
  status?: string;
  has_client_request_id?: boolean;
  allow_server_change?: boolean;
  endpoint_changed?: boolean;
  recovery_in_progress?: boolean;
  chunk_fallback?: boolean;
  accepted?: boolean;
  request_id?: string;
  route?: string;
  body_bytes?: number;
  sequence?: number;
  last_client_sequence?: number;
  expected_sequence?: number;
  next_server_sequence?: number;
  first_available_sequence?: number;
};
